name: vaultify
description: Simply Manage.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  uuid: ^4.4.2
  get: ^4.6.6
  adaptive_theme: ^3.6.0
  hive: ^2.2.3
  supabase_flutter: ^2.6.0
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  flutter_dotenv: ^5.1.0
  introduction_screen: ^3.1.14
  lottie: ^3.1.2
  flutter_vector_icons: ^2.0.0
  settings_ui: ^2.0.2
  future_progress_dialog: ^0.2.1
  encrypt: ^5.0.3
  sensitive_clipboard: ^1.0.0
  swipeable_button_view: ^0.0.2
  pinput: ^5.0.0
  flutter_stripe: ^11.0.0
  http: ^1.2.2
  native_auth: ^1.0.6
  local_auth: ^2.3.0
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  animated_custom_dropdown: ^3.1.1
  mailto: ^2.0.0
  intl: ^0.18.1
  file_picker: ^8.1.4
  permission_handler: ^11.3.1
  csv: ^6.0.0
  toastification: ^2.3.0
  animated_expandable_fab: ^0.0.3
  pointycastle: ^3.9.1
  flutter_secure_storage: ^9.2.2
  tray_manager: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  # Assets
  assets:

    # Environment Variables
    - .env

    # Assets
    - assets/

    # Animations
    - assets/anim/